module.exports = {
  exitToLogin: false,
  isTome: false,
  namespace: '',
  recordAsyncOpt: {},
  refs: {},
  showObjectSwitch: false,
  tableLoading: [false],
  home: {
    asideMenus: [],
    asideShow: true,
    contentFullShow: false,
    curModule: {
      name: '首页',
      route: '/home/Index'
    },
    curPact: {
      name: '广清高速公路扩建工程'
    },
    curProj: {
      name: '建设档案'
    },
    deptList: [],
    headerHeight: 60,
    navMenus: [
      {
        name: '首页',
        route: '/home/Index'
      }
    ],
    noticeList: [],
    selectedIndexDeptID: 0,
    willDoList: []
  },
  log: {
    currentRow: null,
    dataList: [],
    formData: {
      beginDate: '',
      endDate: '',
      keyword: '',
      opType: '',
      userName: '管理员（开发用）'
    }
  },
  notice: {
    addPopMsg: '/popMsg/addPopMsg',
    firstEnter: true,
    getPopMsgByTime: '/popMsg/getPopMsgByTime',
    noticeMsg: [],
    webSocketServerAPI: 'ws://121.12.120.221:7020/veams-gateway/system-baseService/webSocketServer'
  },
  person: {
    allRecordNum: '',
    authorizationInfo: [],
    btnAllOrg: false,
    cASSSO: false,
    certDigest: '',
    certSn: '',
    connectId: '',
    curEntry: null,
    dbName: '',
    deptId: '',
    deptName: '',
    dutyPerson: '',
    eamsLock: '',
    enterDeptId: '',
    enterDeptName: '',
    enterModule: '',
    enterOrgId: '',
    enterOrgName: '',
    enterStr: '',
    isCustomRoute: false,
    isGoWhere: 0,
    mustUKey: '0',
    notFileCanBorrow: false,
    orgId: '',
    orgName: '',
    pactCode: '',
    pactId: '',
    pactName: '',
    pactType: '',
    projId: '',
    projName: '',
    serverSet: 'GD',
    systemUser: false,
    useGpallas: '',
    userId: '',
    userName: ''
  },
  workHistory: {
    currentRow: null,
    dataList: null,
    formData: null
  },
  amsarchivesworkbase: {
    addSelItem: [],
    allAnnexRecords: [],
    allCatalogRecords: [],
    allTomeRecords: [],
    archiversFiles: [],
    catalogFieldSort: [],
    catalogKeyWord: null,
    catalogOrderby: null,
    catalogPage: {
      pageNum: 1,
      pageSize: 100
    },
    catalogRepeatRecords: [],
    catalogTotal: 0,
    checkSG: false,
    compileAnnex: [],
    copyOrShearData: null,
    curSortTreeData: null,
    cutOrCory2Paste: null,
    isBox: false,
    isBtnDisabled: false,
    isTome: true,
    isTomeCollapseShow: false,
    pmisTableData: [],
    selectedAnnexRecords: [],
    selectedCatalogRecords: [],
    selectedDeptID: 0,
    selectedTomeRecords: [],
    sortTreeData: [],
    tomeBasePath: '',
    tomeFieldSort: [],
    tomeKeyWord: null,
    tomeOrderby: null,
    tomePage: {
      pageNum: 1,
      pageSize: 100
    },
    tomeRepeatRecords: [],
    tomeTotal: 0,
    workBasePath: ''
  },
  amscatalogworkbase: {
    addSelItem: [],
    allAnnexRecords: [],
    allCatalogRecords: [],
    allTomeRecords: [],
    archiversFiles: [],
    catalogFieldSort: [],
    catalogKeyWord: null,
    catalogOrderby: null,
    catalogPage: {
      pageNum: 1,
      pageSize: 100
    },
    catalogRepeatRecords: [],
    catalogTotal: 0,
    checkSG: false,
    compileAnnex: [],
    copyOrShearData: null,
    curSortTreeData: null,
    cutOrCory2Paste: null,
    isBox: false,
    isBtnDisabled: false,
    isTome: true,
    isTomeCollapseShow: false,
    pmisTableData: [],
    selectedAnnexRecords: [],
    selectedCatalogRecords: [],
    selectedDeptID: 0,
    selectedTomeRecords: [],
    sortTreeData: [],
    tomeBasePath: '',
    tomeFieldSort: [],
    tomeKeyWord: null,
    tomeOrderby: null,
    tomePage: {
      pageNum: 1,
      pageSize: 100
    },
    tomeRepeatRecords: [],
    tomeTotal: 0,
    workBasePath: ''
  },
  AMSRecordDrawingsManage: {
    addSelItem: [],
    allAnnexRecords: [],
    allCatalogRecords: [],
    allTomeRecords: [],
    archiversFiles: [],
    catalogFieldSort: [],
    catalogKeyWord: null,
    catalogOrderby: null,
    catalogPage: {
      pageNum: 1,
      pageSize: 100
    },
    catalogRepeatRecords: [],
    catalogTotal: 0,
    checkSG: false,
    compileAnnex: [],
    copyOrShearData: null,
    curSortTreeData: null,
    cutOrCory2Paste: null,
    isBox: false,
    isBtnDisabled: false,
    isTome: true,
    isTomeCollapseShow: false,
    pmisTableData: [],
    selectedAnnexRecords: [],
    selectedCatalogRecords: [],
    selectedDeptID: 0,
    selectedTomeRecords: [],
    sortTreeData: [],
    tomeBasePath: '',
    tomeFieldSort: [],
    tomeKeyWord: null,
    tomeOrderby: null,
    tomePage: {
      pageNum: 1,
      pageSize: 100
    },
    tomeRepeatRecords: [],
    tomeTotal: 0,
    workBasePath: ''
  },
  amstomeworkbase: {
    addSelItem: [],
    allAnnexRecords: [],
    allCatalogRecords: [],
    allTomeRecords: [],
    archiversFiles: [],
    catalogFieldSort: [],
    catalogKeyWord: null,
    catalogOrderby: null,
    catalogPage: {
      pageNum: 1,
      pageSize: 100
    },
    catalogRepeatRecords: [],
    catalogTotal: 0,
    checkSG: false,
    compileAnnex: [],
    copyOrShearData: null,
    curSortTreeData: null,
    cutOrCory2Paste: null,
    isBox: false,
    isBtnDisabled: false,
    isTome: true,
    isTomeCollapseShow: false,
    pmisTableData: [],
    selectedAnnexRecords: [],
    selectedCatalogRecords: [],
    selectedDeptID: 0,
    selectedTomeRecords: [],
    sortTreeData: [],
    tomeBasePath: '',
    tomeFieldSort: [],
    tomeKeyWord: null,
    tomeOrderby: null,
    tomePage: {
      pageNum: 1,
      pageSize: 100
    },
    tomeRepeatRecords: [],
    tomeTotal: 0,
    workBasePath: ''
  },
  archivesCompile: {
    addSelItem: [],
    allAnnexRecords: [],
    allCatalogRecords: [],
    allTomeRecords: [],
    archiversFiles: [],
    catalogFieldSort: [],
    catalogKeyWord: null,
    catalogOrderby: null,
    catalogPage: {
      pageNum: 1,
      pageSize: 100
    },
    catalogRepeatRecords: [],
    catalogTotal: 0,
    checkSG: false,
    compileAnnex: [],
    copyOrShearData: null,
    curSortTreeData: null,
    cutOrCory2Paste: null,
    isBox: false,
    isBtnDisabled: false,
    isTome: true,
    isTomeCollapseShow: false,
    pmisTableData: [],
    selectedAnnexRecords: [],
    selectedCatalogRecords: [],
    selectedDeptID: 0,
    selectedTomeRecords: [],
    sortTreeData: [],
    tomeBasePath: '',
    tomeFieldSort: [],
    tomeKeyWord: null,
    tomeOrderby: null,
    tomePage: {
      pageNum: 1,
      pageSize: 100
    },
    tomeRepeatRecords: [],
    tomeTotal: 0,
    workBasePath: ''
  },
  arcstandard: {
    selection: []
  },
  OASystemFileManage: {
    addSelItem: [],
    allAnnexRecords: [],
    allCatalogRecords: [],
    allTomeRecords: [],
    archiversFiles: [],
    catalogFieldSort: [],
    catalogKeyWord: null,
    catalogOrderby: null,
    catalogPage: {
      pageNum: 1,
      pageSize: 100
    },
    catalogRepeatRecords: [],
    catalogTotal: 0,
    checkSG: false,
    compileAnnex: [],
    copyOrShearData: null,
    curSortTreeData: null,
    cutOrCory2Paste: null,
    isBox: false,
    isBtnDisabled: false,
    isTome: true,
    isTomeCollapseShow: false,
    pmisTableData: [],
    selectedAnnexRecords: [],
    selectedCatalogRecords: [],
    selectedDeptID: 0,
    selectedTomeRecords: [],
    sortTreeData: [],
    tomeBasePath: '',
    tomeFieldSort: [],
    tomeKeyWord: null,
    tomeOrderby: null,
    tomePage: {
      pageNum: 1,
      pageSize: 100
    },
    tomeRepeatRecords: [],
    tomeTotal: 0,
    workBasePath: ''
  },
  PMISFileManage: {
    addSelItem: [],
    allAnnexRecords: [],
    allCatalogRecords: [],
    allTomeRecords: [],
    archiversFiles: [],
    catalogFieldSort: [],
    catalogKeyWord: null,
    catalogOrderby: null,
    catalogPage: {
      pageNum: 1,
      pageSize: 100
    },
    catalogRepeatRecords: [],
    catalogTotal: 0,
    checkSG: false,
    compileAnnex: [],
    copyOrShearData: null,
    curSortTreeData: null,
    cutOrCory2Paste: null,
    isBox: false,
    isBtnDisabled: false,
    isTome: true,
    isTomeCollapseShow: false,
    pmisTableData: [],
    selectedAnnexRecords: [],
    selectedCatalogRecords: [],
    selectedDeptID: 0,
    selectedTomeRecords: [],
    sortTreeData: [],
    tomeBasePath: '',
    tomeFieldSort: [],
    tomeKeyWord: null,
    tomeOrderby: null,
    tomePage: {
      pageNum: 1,
      pageSize: 100
    },
    tomeRepeatRecords: [],
    tomeTotal: 0,
    workBasePath: ''
  },
  PmisSysFileManage: {
    addSelItem: [],
    allAnnexRecords: [],
    allCatalogRecords: [],
    allTomeRecords: [],
    archiversFiles: [],
    catalogFieldSort: [],
    catalogKeyWord: null,
    catalogOrderby: null,
    catalogPage: {
      pageNum: 1,
      pageSize: 100
    },
    catalogRepeatRecords: [],
    catalogTotal: 0,
    checkSG: false,
    compileAnnex: [],
    copyOrShearData: null,
    curSortTreeData: null,
    cutOrCory2Paste: null,
    isBox: false,
    isBtnDisabled: false,
    isTome: true,
    isTomeCollapseShow: false,
    pmisTableData: [],
    selectedAnnexRecords: [],
    selectedCatalogRecords: [],
    selectedDeptID: 0,
    selectedTomeRecords: [],
    sortTreeData: [],
    tomeBasePath: '',
    tomeFieldSort: [],
    tomeKeyWord: null,
    tomeOrderby: null,
    tomePage: {
      pageNum: 1,
      pageSize: 100
    },
    tomeRepeatRecords: [],
    tomeTotal: 0,
    workBasePath: ''
  },
  taskList: {
    allTaskList: [],
    selectTaskList: [],
    targetTaskId: ''
  },
  amsorg: {
    listData: null,
    searchInput: null,
    selectRow: null
  },
  archivesProjOverview: {
    archivesList: null,
    currentRow: null
  },
  constructionStats: {
    constructionList: [],
    searchInput: ''
  },
  eamsproj: {
    curPactRow: null,
    curProjRow: null,
    pactList: null,
    projList: null
  },
  fullTextManage: {
    curLeftListData: null,
    leftListData: null,
    rightGroupData: null
  },
  initorg: {
    curOrgList: null,
    curTreeList: null,
    orgList: null,
    treeList: null
  },
  initProj: {
    addConstruData: null,
    addData: null,
    addSuperConsData: null,
    addSuperData: null,
    bidsPublicSettingAddData: null,
    bidsPublicSettingData: null,
    bidsPublicSettingleftData: null,
    bidsPublicSettingRightData: null,
    currentRow: null,
    curTreeList: [],
    leftListData: null,
    modifyFormData: null,
    projPactsByParentPactId: null,
    projTypeSetting: null,
    rightTableData: null
  },
  msgNotice: {
    curLeftListData: null,
    leftListData: null
  },
  orgdeptmag: {
    curOrgDept: null,
    curPerson: null,
    orgDeptTree: null,
    personList: []
  },
  pdfmanage: {
    curPdfType: null,
    CurProj: null,
    projList: null
  },
  printTemplate: {
    curLeftListData: null,
    curRightGroupData: null,
    keyword: null,
    leftListData: null,
    rightGroupData: null,
    typeSearch: null
  },
  projMag: {
    baseTableData: [],
    currentRow: null,
    GPallasPROJ: [],
    searchInput: '',
    tableData: []
  },
  role: {
    allHasPers: null,
    authorityType: 3,
    currentRole: null,
    hasPers: null,
    outAuthorityType: 3,
    rightClickRow: null,
    roleList: null,
    showPermission: null,
    sourcePermission: [],
    templatePers: null,
    typeUnits: null,
    unConfigPers: null
  },
  roleanalysis: {
    currentRow: null,
    formData: {
      userName: ''
    },
    rightClickRow: null,
    roleAnalysisList: [],
    treeList: null,
    userName: ''
  },
  roleTemplate: {
    activeName: '3',
    allEntrancePermission: [],
    authorityType: '3',
    currentRow: null,
    curRoleName: null,
    curTreeData: null,
    rightClickRow: null,
    showPermission: null,
    tableData: [],
    testData: []
  },
  sortTemplate: {
    canNotPaste: true,
    copyCfg: {
      iids: '',
      incCurNode: 0,
      newMid: '',
      newParentId: '',
      oldOrgName: '',
      tag: true
    },
    curOrgList: null,
    curTreeList: null,
    curTreeSelection: null,
    keyWordsStore: null,
    orgList: null,
    treeList: null
  }
}
