name: Build and Release Node Toolkit

on:
  push:
    branches:
      - publish
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual trigger by user'

jobs:
  build:
    runs-on: windows-latest  # 使用 windows 运行器来构建 windows 应用

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # 或者您项目所需的 Node.js 版本

    - name: Install dependencies
      run: npm i

    - name: Lint
      run: |
        npm run lint:eslint
        npm run lint:prettier

    - name: Build Electron App for Windows
      run: npm run build-win64


    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/output/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
